var pathArray = [
    ["ImageResources/Avatars/regionC/avatar_0/frame_0.png","ImageResources/Avatars/regionC/avatar_0/frame_1.png","ImageResources/Avatars/regionC/avatar_0/frame_2.png"],
    ["ImageResources/Avatars/regionC/avatar_1/frame_0.png","ImageResources/Avatars/regionC/avatar_1/frame_1.png","ImageResources/Avatars/regionC/avatar_1/frame_2.png","ImageResources/Avatars/regionC/avatar_1/frame_3.png","ImageResources/Avatars/regionC/avatar_1/frame_4.png","ImageResources/Avatars/regionC/avatar_1/frame_5.png","ImageResources/Avatars/regionC/avatar_1/frame_6.png","ImageResources/Avatars/regionC/avatar_1/frame_7.png","ImageResources/Avatars/regionC/avatar_1/frame_8.png","ImageResources/Avatars/regionC/avatar_1/frame_9.png","ImageResources/Avatars/regionC/avatar_1/frame_10.png","ImageResources/Avatars/regionC/avatar_1/frame_11.png","ImageResources/Avatars/regionC/avatar_1/frame_12.png","ImageResources/Avatars/regionC/avatar_1/frame_13.png","ImageResources/Avatars/regionC/avatar_1/frame_14.png"],
    ["ImageResources/Avatars/regionC/avatar_2/frame_0.png","ImageResources/Avatars/regionC/avatar_2/frame_1.png","ImageResources/Avatars/regionC/avatar_2/frame_2.png","ImageResources/Avatars/regionC/avatar_2/frame_3.png","ImageResources/Avatars/regionC/avatar_2/frame_4.png","ImageResources/Avatars/regionC/avatar_2/frame_5.png","ImageResources/Avatars/regionC/avatar_2/frame_6.png","ImageResources/Avatars/regionC/avatar_2/frame_7.png","ImageResources/Avatars/regionC/avatar_2/frame_8.png","ImageResources/Avatars/regionC/avatar_2/frame_9.png","ImageResources/Avatars/regionC/avatar_2/frame_10.png","ImageResources/Avatars/regionC/avatar_2/frame_11.png"],
    ["ImageResources/Avatars/regionC/avatar_3/frame_0.png","ImageResources/Avatars/regionC/avatar_3/frame_1.png","ImageResources/Avatars/regionC/avatar_3/frame_2.png","ImageResources/Avatars/regionC/avatar_3/frame_3.png","ImageResources/Avatars/regionC/avatar_3/frame_4.png"],
    ["ImageResources/Avatars/regionC/avatar_4/frame_0.png","ImageResources/Avatars/regionC/avatar_4/frame_1.png","ImageResources/Avatars/regionC/avatar_4/frame_2.png","ImageResources/Avatars/regionC/avatar_4/frame_3.png","ImageResources/Avatars/regionC/avatar_4/frame_4.png","ImageResources/Avatars/regionC/avatar_4/frame_5.png","ImageResources/Avatars/regionC/avatar_4/frame_6.png","ImageResources/Avatars/regionC/avatar_4/frame_7.png"],
    ["ImageResources/Avatars/regionC/avatar_5/frame_0.png","ImageResources/Avatars/regionC/avatar_5/frame_1.png","ImageResources/Avatars/regionC/avatar_5/frame_2.png","ImageResources/Avatars/regionC/avatar_5/frame_3.png","ImageResources/Avatars/regionC/avatar_5/frame_4.png","ImageResources/Avatars/regionC/avatar_5/frame_5.png"],
    ["ImageResources/Avatars/regionC/avatar_6/frame_0.png","ImageResources/Avatars/regionC/avatar_6/frame_1.png","ImageResources/Avatars/regionC/avatar_6/frame_2.png","ImageResources/Avatars/regionC/avatar_6/frame_3.png","ImageResources/Avatars/regionC/avatar_6/frame_4.png"],
    ["ImageResources/Avatars/regionC/avatar_7/frame_0.png","ImageResources/Avatars/regionC/avatar_7/frame_1.png","ImageResources/Avatars/regionC/avatar_7/frame_2.png","ImageResources/Avatars/regionC/avatar_7/frame_3.png","ImageResources/Avatars/regionC/avatar_7/frame_4.png","ImageResources/Avatars/regionC/avatar_7/frame_5.png","ImageResources/Avatars/regionC/avatar_7/frame_6.png","ImageResources/Avatars/regionC/avatar_7/frame_7.png"],
];

var currentLevel = localStorage.getItem("regionC");