var pathArray = [
    ["ImageResources/Avatars/regionD/avatar_0/frame_0.png","ImageResources/Avatars/regionD/avatar_0/frame_1.png","ImageResources/Avatars/regionD/avatar_0/frame_2.png","ImageResources/Avatars/regionD/avatar_0/frame_3.png","ImageResources/Avatars/regionD/avatar_0/frame_4.png","ImageResources/Avatars/regionD/avatar_0/frame_5.png"],
    ["ImageResources/Avatars/regionD/avatar_1/frame_0.png","ImageResources/Avatars/regionD/avatar_1/frame_1.png","ImageResources/Avatars/regionD/avatar_1/frame_2.png","ImageResources/Avatars/regionD/avatar_1/frame_3.png","ImageResources/Avatars/regionD/avatar_1/frame_4.png"],
    ["ImageResources/Avatars/regionD/avatar_2/frame_0.png","ImageResources/Avatars/regionD/avatar_2/frame_1.png","ImageResources/Avatars/regionD/avatar_2/frame_2.png","ImageResources/Avatars/regionD/avatar_2/frame_3.png","ImageResources/Avatars/regionD/avatar_2/frame_4.png","ImageResources/Avatars/regionD/avatar_2/frame_5.png","ImageResources/Avatars/regionD/avatar_2/frame_6.png","ImageResources/Avatars/regionD/avatar_2/frame_7.png"],
    ["ImageResources/Avatars/regionD/avatar_3/frame_0.png","ImageResources/Avatars/regionD/avatar_3/frame_1.png"],
    ["ImageResources/Avatars/regionD/avatar_4/frame_0.png","ImageResources/Avatars/regionD/avatar_4/frame_1.png"],
    ["ImageResources/Avatars/regionD/avatar_5/frame_0.png","ImageResources/Avatars/regionD/avatar_5/frame_1.png","ImageResources/Avatars/regionD/avatar_5/frame_2.png","ImageResources/Avatars/regionD/avatar_5/frame_3.png","ImageResources/Avatars/regionD/avatar_5/frame_4.png","ImageResources/Avatars/regionD/avatar_5/frame_5.png","ImageResources/Avatars/regionD/avatar_5/frame_6.png","ImageResources/Avatars/regionD/avatar_5/frame_7.png","ImageResources/Avatars/regionD/avatar_5/frame_8.png","ImageResources/Avatars/regionD/avatar_5/frame_9.png"],
    ["ImageResources/Avatars/regionD/avatar_6/frame_0.png","ImageResources/Avatars/regionD/avatar_6/frame_1.png","ImageResources/Avatars/regionD/avatar_6/frame_2.png","ImageResources/Avatars/regionD/avatar_6/frame_3.png","ImageResources/Avatars/regionD/avatar_6/frame_4.png"],
    ["ImageResources/Avatars/regionD/avatar_7/frame_0.png","ImageResources/Avatars/regionD/avatar_7/frame_1.png"],
];

var currentLevel = localStorage.getItem("regionD");