var pathArray = [
    ["ImageResources/Avatars/regionG/avatar_0/frame_0.png","ImageResources/Avatars/regionG/avatar_0/frame_1.png","ImageResources/Avatars/regionG/avatar_0/frame_2.png","ImageResources/Avatars/regionG/avatar_0/frame_3.png"],
    ["ImageResources/Avatars/regionG/avatar_1/frame_0.png","ImageResources/Avatars/regionG/avatar_1/frame_1.png","ImageResources/Avatars/regionG/avatar_1/frame_2.png","ImageResources/Avatars/regionG/avatar_1/frame_3.png"],
    ["ImageResources/Avatars/regionG/avatar_2/frame_0.png","ImageResources/Avatars/regionG/avatar_2/frame_1.png","ImageResources/Avatars/regionG/avatar_2/frame_2.png","ImageResources/Avatars/regionG/avatar_2/frame_3.png","ImageResources/Avatars/regionG/avatar_2/frame_4.png","ImageResources/Avatars/regionG/avatar_2/frame_5.png"],
    ["ImageResources/Avatars/regionG/avatar_3/frame_0.png","ImageResources/Avatars/regionG/avatar_3/frame_1.png","ImageResources/Avatars/regionG/avatar_3/frame_2.png","ImageResources/Avatars/regionG/avatar_3/frame_3.png","ImageResources/Avatars/regionG/avatar_3/frame_4.png","ImageResources/Avatars/regionG/avatar_3/frame_5.png","ImageResources/Avatars/regionG/avatar_3/frame_6.png","ImageResources/Avatars/regionG/avatar_3/frame_7.png","ImageResources/Avatars/regionG/avatar_3/frame_8.png","ImageResources/Avatars/regionG/avatar_3/frame_9.png"],
    ["ImageResources/Avatars/regionG/avatar_4/frame_0.png","ImageResources/Avatars/regionG/avatar_4/frame_1.png","ImageResources/Avatars/regionG/avatar_4/frame_2.png","ImageResources/Avatars/regionG/avatar_4/frame_3.png","ImageResources/Avatars/regionG/avatar_4/frame_4.png","ImageResources/Avatars/regionG/avatar_4/frame_5.png","ImageResources/Avatars/regionG/avatar_4/frame_6.png","ImageResources/Avatars/regionG/avatar_4/frame_7.png","ImageResources/Avatars/regionG/avatar_4/frame_8.png","ImageResources/Avatars/regionG/avatar_4/frame_9.png","ImageResources/Avatars/regionG/avatar_4/frame_10.png"],
    ["ImageResources/Avatars/regionG/avatar_5/frame_0.png","ImageResources/Avatars/regionG/avatar_5/frame_1.png","ImageResources/Avatars/regionG/avatar_5/frame_2.png","ImageResources/Avatars/regionG/avatar_5/frame_3.png","ImageResources/Avatars/regionG/avatar_5/frame_4.png","ImageResources/Avatars/regionG/avatar_5/frame_5.png","ImageResources/Avatars/regionG/avatar_5/frame_6.png","ImageResources/Avatars/regionG/avatar_5/frame_7.png"],
    ["ImageResources/Avatars/regionG/avatar_6/frame_0.png","ImageResources/Avatars/regionG/avatar_6/frame_1.png","ImageResources/Avatars/regionG/avatar_6/frame_2.png","ImageResources/Avatars/regionG/avatar_6/frame_3.png","ImageResources/Avatars/regionG/avatar_6/frame_4.png","ImageResources/Avatars/regionG/avatar_6/frame_5.png","ImageResources/Avatars/regionG/avatar_6/frame_6.png","ImageResources/Avatars/regionG/avatar_6/frame_7.png","ImageResources/Avatars/regionG/avatar_6/frame_8.png","ImageResources/Avatars/regionG/avatar_6/frame_9.png","ImageResources/Avatars/regionG/avatar_6/frame_10.png","ImageResources/Avatars/regionG/avatar_6/frame_11.png","ImageResources/Avatars/regionG/avatar_6/frame_12.png","ImageResources/Avatars/regionG/avatar_6/frame_13.png","ImageResources/Avatars/regionG/avatar_6/frame_14.png"],
    ["ImageResources/Avatars/regionG/avatar_7/frame_0.png","ImageResources/Avatars/regionG/avatar_7/frame_1.png"],
];


var localLevel = parseInt(localStorage.getItem("regionG")) + 1||1;

console.log(localLevel + " Level loaded");