var pathArray = [
    ["ImageResources/Avatars/regionF/avatar_0/frame_0.png","ImageResources/Avatars/regionF/avatar_0/frame_1.png","ImageResources/Avatars/regionF/avatar_0/frame_2.png","ImageResources/Avatars/regionF/avatar_0/frame_3.png","ImageResources/Avatars/regionF/avatar_0/frame_4.png","ImageResources/Avatars/regionF/avatar_0/frame_5.png"],
    ["ImageResources/Avatars/regionF/avatar_1/frame_0.png","ImageResources/Avatars/regionF/avatar_1/frame_1.png","ImageResources/Avatars/regionF/avatar_1/frame_2.png","ImageResources/Avatars/regionF/avatar_1/frame_3.png","ImageResources/Avatars/regionF/avatar_1/frame_4.png","ImageResources/Avatars/regionF/avatar_1/frame_5.png","ImageResources/Avatars/regionF/avatar_1/frame_6.png","ImageResources/Avatars/regionF/avatar_1/frame_7.png","ImageResources/Avatars/regionF/avatar_1/frame_8.png","ImageResources/Avatars/regionF/avatar_1/frame_9.png"],
    ["ImageResources/Avatars/regionF/avatar_2/frame_0.png","ImageResources/Avatars/regionF/avatar_2/frame_1.png","ImageResources/Avatars/regionF/avatar_2/frame_2.png","ImageResources/Avatars/regionF/avatar_2/frame_3.png"],
    ["ImageResources/Avatars/regionF/avatar_3/frame_0.png","ImageResources/Avatars/regionF/avatar_3/frame_1.png","ImageResources/Avatars/regionF/avatar_3/frame_2.png","ImageResources/Avatars/regionF/avatar_3/frame_3.png","ImageResources/Avatars/regionF/avatar_3/frame_4.png","ImageResources/Avatars/regionF/avatar_3/frame_5.png"],
    ["ImageResources/Avatars/regionF/avatar_4/frame_0.png","ImageResources/Avatars/regionF/avatar_4/frame_1.png","ImageResources/Avatars/regionF/avatar_4/frame_2.png","ImageResources/Avatars/regionF/avatar_4/frame_3.png","ImageResources/Avatars/regionF/avatar_4/frame_4.png","ImageResources/Avatars/regionF/avatar_4/frame_5.png"],
    ["ImageResources/Avatars/regionF/avatar_5/frame_0.png","ImageResources/Avatars/regionF/avatar_5/frame_1.png","ImageResources/Avatars/regionF/avatar_5/frame_2.png","ImageResources/Avatars/regionF/avatar_5/frame_3.png"],
    ["ImageResources/Avatars/regionF/avatar_6/frame_0.png","ImageResources/Avatars/regionF/avatar_6/frame_1.png","ImageResources/Avatars/regionF/avatar_6/frame_2.png","ImageResources/Avatars/regionF/avatar_6/frame_3.png","ImageResources/Avatars/regionF/avatar_6/frame_4.png","ImageResources/Avatars/regionF/avatar_6/frame_5.png","ImageResources/Avatars/regionF/avatar_6/frame_6.png","ImageResources/Avatars/regionF/avatar_6/frame_7.png","ImageResources/Avatars/regionF/avatar_6/frame_8.png","ImageResources/Avatars/regionF/avatar_6/frame_9.png","ImageResources/Avatars/regionF/avatar_6/frame_10.png","ImageResources/Avatars/regionF/avatar_6/frame_11.png"],
    ["ImageResources/Avatars/regionF/avatar_7/frame_0.png","ImageResources/Avatars/regionF/avatar_7/frame_1.png","ImageResources/Avatars/regionF/avatar_7/frame_2.png","ImageResources/Avatars/regionF/avatar_7/frame_3.png"],
];


var localLevel = parseInt(localStorage.getItem("regionF")) + 1;

console.log(localLevel + " Level loaded");